#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean myTurbulenceModels
wclean incompressible
wclean compressible
wclean schemes
wcleanLnIncludeAll

#------------------------------------------------------------------------------
