#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

wmakeLnInclude myInterfacialModels
wmake $targetType myTwoPhaseSystem
wmake $targetType myInterfacialModels
wmake $targetType myPhaseCompressibleMyTurbulenceModels
wmake $targetType

#------------------------------------------------------------------------------
