#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso myTwoPhaseSystem
wclean libso myInterfacialModels
wclean libso myPhaseCompressibleMyTurbulenceModels
wclean

#------------------------------------------------------------------------------
